#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.md from the licence files of the dependencies
# CPM actually fetched, so the notice can never drift from what is really linked.
# Run after changing a dependency or bumping a version.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPS="$ROOT/build/_deps"
OUT="$ROOT/THIRD_PARTY_LICENSES.md"

if [ ! -d "$DEPS" ]; then
  echo "error: $DEPS not found. Configure the project first (cmake -B build)." >&2
  exit 1
fi

{
  echo "# Third-Party Licences"
  echo
  echo "Generated by \`tools/gen_third_party_licenses.sh\` from the dependencies"
  echo "actually fetched into \`build/_deps\`. Ship this file with the game."
  echo
  echo "| Component | Licence | Shipped in the game binary? |"
  echo "|---|---|---|"
  echo "| raylib | zlib/libpng | Yes (statically linked) |"
  echo "| EnTT | MIT | Yes (header-only) |"
  echo "| toml++ | MIT | Yes (header-only) |"
  echo "| nlohmann/json | MIT | Yes (header-only) |"
  echo "| Catch2 | Boost Software License 1.0 | **No** — test binary only |"
  echo "| CPM.cmake | MIT | **No** — build-time only |"
  echo
  for d in raylib-src entt-src tomlplusplus-src json-src catch2-src; do
    f=$(find "$DEPS/$d" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'COPYING*' \) 2>/dev/null | head -1 || true)
    [ -n "$f" ] || continue
    echo "---"
    echo
    echo "## $d"
    echo
    echo '```'
    cat "$f"
    echo '```'
    echo
  done
} > "$OUT"
echo "wrote $OUT"
