#!/usr/bin/env python3
"""Generates map TOML from waypoints.

    python3 tools/make_map.py

The first hand-authored map shipped with its tiles block disagreeing with its
path: a vertical run sat at x=12 while the corners were written at x=13. Nothing
caught it until the route was walked by eye. Every map since is GENERATED from
its waypoints, so the two cannot disagree -- the tiles are derived, not authored.

This also verifies, before writing anything:
  - every segment is axis-aligned (the sim lerps straight lines only)
  - every tile is inside the grid
  - the route does not cross itself (ambiguous for the player to read)
  - the first and last waypoints sit on a grid edge
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRID_W, GRID_H = 22, 11  # fixed by the renderer's virtual resolution


def route_tiles(waypoints):
    """Every tile the route covers, in order, with no duplicates."""
    tiles = []
    for (x0, y0), (x1, y1) in zip(waypoints, waypoints[1:]):
        if x0 != x1 and y0 != y1:
            raise ValueError(f"segment ({x0},{y0})->({x1},{y1}) is not axis-aligned")
        dx = (x1 > x0) - (x1 < x0)
        dy = (y1 > y0) - (y1 < y0)
        steps = max(abs(x1 - x0), abs(y1 - y0))
        for i in range(steps + 1):
            t = (x0 + dx * i, y0 + dy * i)
            if not tiles or tiles[-1] != t:
                tiles.append(t)
    # Drop consecutive duplicates introduced at corners.
    out = []
    for t in tiles:
        if not out or out[-1] != t:
            out.append(t)
    return out


def verify(name, waypoints):
    tiles = route_tiles(waypoints)
    for (x, y) in tiles:
        if not (0 <= x < GRID_W and 0 <= y < GRID_H):
            raise ValueError(f"{name}: tile ({x},{y}) is outside the {GRID_W}x{GRID_H} grid")

    seen = set()
    for t in tiles:
        if t in seen:
            raise ValueError(f"{name}: route crosses itself at {t}")
        seen.add(t)

    for label, (x, y) in (("spawn", waypoints[0]), ("exit", waypoints[-1])):
        on_edge = x == 0 or y == 0 or x == GRID_W - 1 or y == GRID_H - 1
        if not on_edge:
            raise ValueError(f"{name}: {label} ({x},{y}) is not on a grid edge")
    return tiles


def tile_rows(tiles):
    grid = [["." for _ in range(GRID_W)] for _ in range(GRID_H)]
    for (x, y) in tiles:
        grid[y][x] = "="
    sx, sy = tiles[0]
    ex, ey = tiles[-1]
    grid[sy][sx] = "S"
    grid[ey][ex] = "E"
    return ["".join(row) for row in grid]


def emit(m):
    tiles = verify(m["id"], m["path"])
    rows = tile_rows(tiles)
    wp = ",".join(f"[{x},{y}]" for x, y in m["path"])
    pool = "\n\n".join(
        f'[[waves.pool]]\nenemy = "{e}"\nfromWave = {w}' for e, w in m["pool"])
    bosses = "\n\n".join(
        f'[[waves.boss]]\nwave = {w}\nenemy = "{e}"' for w, e in m["bosses"])

    return f'''# GENERATED by tools/make_map.py -- edit the spec there, not this file.
# The tiles block is derived from `path`, so the two cannot disagree.

[map]
id = "{m['id']}"
name = "{m['name']}"
order = {m['order']}
blurb = "{m['blurb']}"
gridW = {GRID_W}
gridH = {GRID_H}
startGold = {m['startGold']}
buildTime = {m['buildTime']}

# {m['blurb']}

# '.' buildable   '#' blocked scenery   '=' path   'S' spawn   'E' exit
tiles = """
{chr(10).join(rows)}
"""

path = [{wp}]

[waves]
count = 50
countBase = {m['countBase']}
countPerWave = {m['countPerWave']}
intervalBase = {m['intervalBase']}
intervalDecay = 0.985
intervalMin = 0.30
hpPerWave = {m['hpPerWave']}
hpCurveExp = {m['hpCurveExp']}
armorPerWave = {m['armorPerWave']}
bountyPerWave = 1.02
secondaryFromWave = 4
secondaryFraction = 0.6
secondaryDelay = 2.5
delay = 5.0
bossDelay = 9.0

{bosses}

{pool}
'''


# Difficulty rises across the five maps: later maps start with less relative
# gold, ramp harder and armour up faster. Each is 22x11 because the renderer's
# virtual resolution fixes the board size.
MAPS = [
    {
        "id": "ashen-wastes", "order": 2, "name": "Ashen Wastes",
        "blurb": "Three long straights: good for reach, punishing for short range.",
        "path": [(0, 1), (18, 1), (18, 4), (3, 4), (3, 7), (19, 7), (19, 10), (21, 10)],
        "startGold": 520, "buildTime": 12.0,
        "countBase": 9, "countPerWave": 0.42, "intervalBase": 0.88,
        "hpPerWave": 1.058, "hpCurveExp": 1.19, "armorPerWave": 0.13,
        "bosses": [(25, "boss_cinder_brute"), (50, "boss_cinder_colossus")],
        "pool": [("ash_slime", 1), ("ash_wolf", 4), ("ash_goblin", 7), ("ash_wraith", 11)],
    },
    {
        "id": "frostmere", "order": 3, "name": "Frostmere",
        "blurb": "A long winding route. Every tower gets several passes if placed well.",
        "path": [(0, 1), (4, 1), (4, 5), (10, 5), (10, 1), (15, 1), (15, 9), (6, 9),
                 (6, 7), (2, 7), (2, 10), (21, 10)],
        "startGold": 540, "buildTime": 12.0,
        "countBase": 10, "countPerWave": 0.45, "intervalBase": 0.86,
        "hpPerWave": 1.060, "hpCurveExp": 1.20, "armorPerWave": 0.14,
        "bosses": [(25, "boss_rime_stalker"), (50, "boss_rime_tyrant")],
        "pool": [("frost_slime", 1), ("frost_wolf", 4), ("frost_goblin", 7),
                 ("frost_wraith", 10)],
    },
    {
        "id": "blightmarsh", "order": 4, "name": "Blightmarsh",
        "blurb": "Wide open ground with few corners: coverage matters more than depth.",
        "path": [(0, 9), (5, 9), (5, 2), (11, 2), (11, 7), (17, 7), (17, 2), (21, 2)],
        "startGold": 560, "buildTime": 11.0,
        "countBase": 11, "countPerWave": 0.48, "intervalBase": 0.84,
        "hpPerWave": 1.062, "hpCurveExp": 1.21, "armorPerWave": 0.15,
        "bosses": [(25, "boss_plague_carrier"), (50, "boss_plague_mother")],
        "pool": [("blight_slime", 1), ("blight_wolf", 4), ("blight_goblin", 6),
                 ("blight_wraith", 9)],
    },
    {
        "id": "obsidian-gate", "order": 5, "name": "Obsidian Gate",
        "blurb": "The last map. Heavily armoured, resistant to everything, and long.",
        "path": [(0, 5), (3, 5), (3, 1), (8, 1), (8, 8), (13, 8), (13, 1), (18, 1),
                 (18, 6), (21, 6)],
        "startGold": 580, "buildTime": 11.0,
        "countBase": 12, "countPerWave": 0.52, "intervalBase": 0.82,
        "hpPerWave": 1.065, "hpCurveExp": 1.22, "armorPerWave": 0.17,
        "bosses": [(25, "boss_gate_sentinel"), (50, "boss_gate_warden")],
        "pool": [("obsidian_slime", 1), ("obsidian_wolf", 3), ("obsidian_goblin", 6),
                 ("obsidian_wraith", 9)],
    },
]


def main():
    out_dir = os.path.join(ROOT, "content", "maps")
    for m in MAPS:
        text = emit(m)
        path = os.path.join(out_dir, m["id"] + ".toml")
        with open(path, "w") as f:
            f.write(text)
        tiles = route_tiles(m["path"])
        print(f"  {m['id']:16s} {len(tiles):3d} path tiles, "
              f"{len(m['path'])} waypoints -> {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    try:
        main()
    except ValueError as e:
        print(f"map spec rejected: {e}", file=sys.stderr)
        sys.exit(1)
